export const projects = [
  {
    slug: "autocaravanas-bahia",
    title: "Autocaravanas Bahía",
    description: "Una web bilingüe para presentar una flota de autocaravanas y facilitar solicitudes de reserva.",
    image: "/portfolio/Autocaravanasbahia.webp",
    url: "https://www.autocaravanasbahia.es/",
    sector: "Alquiler de autocaravanas · Alicante",
    services: ["Diseño web", "Desarrollo web", "Contenido multiidioma"],
    challenge: "El visitante necesita conocer los vehículos y las condiciones del servicio antes de consultar disponibilidad. El proyecto reúne la presentación de la flota, información de rutas y una vía para solicitar una reserva.",
    work: ["Presentación de los vehículos y la actividad de alquiler.", "Contenido bilingüe para atender a públicos distintos.", "Mapa interactivo de rutas y solicitud de reserva."],
    value: "El recorrido conecta la información que necesita el viajero con la solicitud de reserva. La presentación de la flota y las rutas permite valorar el servicio antes de realizar una consulta.",
    service: "desarrollo-web",
    serviceLinks: [{ label: "Diseño web", href: "/servicios/diseno-web" }, { label: "Desarrollo web", href: "/servicios/desarrollo-web" }],
    serviceLabel: "Ver desarrollo web a medida",
  },
  {
    slug: "bostak-inmobiliaria",
    title: "Bostak Inmobiliaria",
    description: "Web inmobiliaria moderna con catálogo dinámico de inmuebles en venta y alquiler, fichas detalladas y captación de propietarios.",
    image: "/portfolio/bostak-inmobiliaria.webp",
    url: "https://bostakinmobiliaria.vercel.app/",
    sector: "Estudio inmobiliario · Bilbao",
    services: ["Diseño web", "Catálogo dinámico", "Captación de leads"],
    challenge: "Organizar un catálogo inmobiliario amplio con filtros por zona, tipología y presupuesto, facilitando tanto la búsqueda de compradores como la captación de nuevos propietarios.",
    work: [
      "Catálogo visual de viviendas con filtros de zona, precio y características.",
      "Fichas técnicas con galería multimedia, distribución y especificaciones del inmueble.",
      "Embudos de contacto directo para valoración y venta de propiedades.",
    ],
    value: "La plataforma digitaliza la gestión inmobiliaria del estudio, transmitiendo transparencia y profesionalidad en cada etapa de la compraventa.",
    service: "desarrollo-web",
    serviceLinks: [{ label: "Diseño web", href: "/servicios/diseno-web" }, { label: "Desarrollo web", href: "/servicios/desarrollo-web" }],
    serviceLabel: "Ver desarrollo web a medida",
  },
  {
    slug: "cao",
    title: "CAO",
    description: "Diseño web corporativo con identidad visual contemporánea y experiencia de usuario optimizada para conversión.",
    image: "/portfolio/cao.webp",
    url: "https://cao-brown.vercel.app/",
    sector: "Estudio de arquitectura e interiorismo",
    services: ["Diseño web", "Identidad visual", "Optimización UX"],
    challenge: "Transmitir la sensibilidad estética, rigor arquitectónico y exclusividad de sus proyectos mediante una interfaz minimalista, cuidada y de carga instantánea.",
    work: ["Diseño visual con retícula editorial y tipografía contemporánea.", "Presentación inmersiva del catálogo de obras y proyectos.", "Arquitectura optimizada para navegación fluida y conversión."],
    value: "La web posiciona al estudio en un segmento de alta gama, permitiendo a clientes potenciales explorar su trabajo con fluidez y solicitar una primera reunión de forma directa.",
    service: "diseno-web",
    serviceLinks: [{ label: "Diseño web", href: "/servicios/diseno-web" }],
    serviceLabel: "Ver diseño web para empresas",
  },
  {
    slug: "clinica-dental-regos",
    title: "Clínica Dental Regos",
    description: "Web corporativa médica para grupo odontológico con 2 sedes en Galicia, catálogo de especialidades clínicas y reserva de cita online.",
    image: "/portfolio/clinica-dental-regos.webp",
    url: "https://clinica-dental-regos.vercel.app/",
    sector: "Clínica odontológica · Ordes y Santiago",
    services: ["Diseño web", "Estructura multisede", "Cita previa"],
    challenge: "Transmitir más de 20 años de experiencia clínica y docencia universitaria en una interfaz sobria, accesible y multisede que facilite pedir cita en Ordes o Santiago.",
    work: [
      "Diseño médico de alta precisión que proyecta rigor científico y cercanía.",
      "Arquitectura multisede con datos de contacto, horarios y geolocalización independiente.",
      "Catálogo de tratamientos avanzados con reserva de cita digital integrada.",
    ],
    value: "La web consolida la autoridad médica de la clínica en Galicia y optimiza el flujo de captación de pacientes para ambas sedes.",
    service: "diseno-web",
    serviceLinks: [{ label: "Diseño web", href: "/servicios/diseno-web" }],
    serviceLabel: "Ver diseño web para empresas",
  },
  {
    slug: "jardineria-el-cuetu",
    title: "Jardinería El Cuetu",
    description: "Una web de jardinería con identidad visual propia, galería de trabajos y formulario de contacto.",
    image: "/portfolio/cuetu.webp",
    url: "https://jardineria-elcuetu.vercel.app/",
    sector: "Servicios de jardinería · Asturias",
    services: ["Diseño web", "Galería de proyectos", "Formulario de contacto"],
    challenge: "En un servicio de jardinería, enseñar trabajos ayuda al visitante a valorar la oferta. El proyecto combina una presentación visual de la actividad con una galería y un canal para consultar un trabajo concreto.",
    work: ["Diseño visual con referencias al entorno natural de la actividad.", "Galería para presentar trabajos de jardinería.", "Formulario de contacto integrado en el recorrido de la web."],
    value: "La estructura permite pasar de conocer la actividad y ver ejemplos a realizar una consulta. La galería ayuda a valorar el tipo de trabajo y el formulario facilita iniciar una conversación sobre el proyecto.",
    service: "diseno-web",
    serviceLinks: [{ label: "Diseño web", href: "/servicios/diseno-web" }],
    serviceLabel: "Ver diseño web para empresas",
  },
  {
    slug: "uno-dental",
    title: "Uno Dental",
    description: "Web clínica para centro odontológico integral con presentación de tratamientos, equipo profesional y solicitud de cita previa.",
    image: "/portfolio/uno-dental.webp",
    url: "https://unodental.vercel.app/",
    sector: "Clínica dental · Valladolid",
    services: ["Diseño web", "Identidad visual", "Captación local"],
    challenge: "Presentar una clínica dental familiar con más de 16 años de trayectoria en Valladolid mediante un diseño cálido, moderno y centrado en la tranquilidad del paciente.",
    work: [
      "Diseño limpio y humano concebido para generar confianza y reducir el estrés dental.",
      "Presentación detallada de especialidades: implantología, ortodoncia y estética.",
      "Llamadas a la acción claras para solicitud de cita previa y contacto telefónico.",
    ],
    value: "Mejora la visibilidad del centro en el ámbito local y agiliza la entrada de consultas y primeras visitas a la clínica.",
    service: "diseno-web",
    serviceLinks: [{ label: "Diseño web", href: "/servicios/diseno-web" }],
    serviceLabel: "Ver diseño web para empresas",
  },
] as const;

export type Project = (typeof projects)[number];
